### ISSUE TITLE
Problem with datetime values in ExposureDetails

### ISSUE THREAD

**Issue by gcerbone** [Enzoic/enzoic-dotnet-client#1]
The REST API will return null values for ExposureDetails Date and DateAdded if the date is unknown.  However, ExposureDetails.Date and ExposureDetails.DateAdded are defined as DateTime, which will not allow nulls.  They should be changed to DateTime? to allow nulls.

**Comment by Enzoic** [comment]
This should be fixed in version 1.0.1.2 published to Nuget.  Thanks for the heads up.
